# Generated by Django 4.2.11 on 2026-05-20 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('monitoring_enabled', models.BooleanField(default=False)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily spending limit in NGN. NULL means no limit.', max_digits=10, null=True)),
            ],
            options={
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('service_type', models.CharField(blank=True, default='', help_text='e.g. Food & Beverage, Bookstore, Supplies', max_length=50)),
                ('store_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'seller_profiles',
            },
        ),
    ]
