# Generated by Django 4.2.11 on 2026-05-20 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentstudentlink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentlink',
            unique_together={('parent', 'student_id')},
        ),
    ]
