# Generated by Django 4.2.11 on 2026-05-20 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('topup', 'Top-up'), ('refund', 'Refund')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('declined', 'Declined')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_date'], name='payments_tr_transac_7d3386_idx'), models.Index(fields=['wallet', 'transaction_date'], name='payments_tr_wallet__0ef4f8_idx'), models.Index(fields=['payment_status'], name='payments_tr_payment_0b9bd0_idx')],
            },
        ),
    ]
